[2024-12-06T14:19:28.582+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T14:19:28.591+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-07-11T13:14:00+00:00 [queued]>
[2024-12-06T14:19:28.595+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-07-11T13:14:00+00:00 [queued]>
[2024-12-06T14:19:28.596+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T14:19:28.603+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2016-07-11 13:14:00+00:00
[2024-12-06T14:19:28.607+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1927) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T14:19:28.608+0000] {standard_task_runner.py:72} INFO - Started process 1930 to run task
[2024-12-06T14:19:28.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2016-07-11T13:14:00+00:00', '--job-id', '1789', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmpi6o9dfxl']
[2024-12-06T14:19:28.610+0000] {standard_task_runner.py:105} INFO - Job 1789: Subtask PushAllInOne
[2024-12-06T14:19:28.633+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-07-11T13:14:00+00:00 [running]> on host 6b4257da02f0
[2024-12-06T14:19:28.677+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2016-07-11T13:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2016-07-11T13:14:00+00:00'
[2024-12-06T14:19:28.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T14:19:30.942+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-06T14:19:30.943+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T14:19:30.950+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T14:19:30.950+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2016-07-11T13:14:00+00:00, execution_date=20160711T131400, start_date=20241206T141928, end_date=20241206T141930
[2024-12-06T14:19:30.987+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T14:19:30.996+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T14:19:30.998+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
