[2024-12-06T11:30:59.942+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T11:30:59.953+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-01-08T11:32:00+00:00 [queued]>
[2024-12-06T11:30:59.961+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-01-08T11:32:00+00:00 [queued]>
[2024-12-06T11:30:59.961+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T11:30:59.969+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-01-08 11:32:00+00:00
[2024-12-06T11:30:59.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T11:30:59.975+0000] {standard_task_runner.py:72} INFO - Started process 218 to run task
[2024-12-06T11:30:59.975+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2024-01-08T11:32:00+00:00', '--job-id', '692', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmpaxr6nb9s']
[2024-12-06T11:30:59.977+0000] {standard_task_runner.py:105} INFO - Job 692: Subtask PushAllInOne
[2024-12-06T11:31:00.016+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-01-08T11:32:00+00:00 [running]> on host d88abb179e8d
[2024-12-06T11:31:00.085+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T11:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-08T11:32:00+00:00'
[2024-12-06T11:31:00.087+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T11:31:04.094+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-06T11:31:04.095+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T11:31:04.100+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T11:31:04.100+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2024-01-08T11:32:00+00:00, execution_date=20240108T113200, start_date=20241206T113059, end_date=20241206T113104
[2024-12-06T11:31:04.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T11:31:04.127+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T11:31:04.128+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
