[2024-12-12T11:30:01.559+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T11:30:01.571+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rtve_schedule_scraper.scrape_rtve_task scheduled__2024-12-12T05:30:00+00:00 [queued]>
[2024-12-12T11:30:01.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rtve_schedule_scraper.scrape_rtve_task scheduled__2024-12-12T05:30:00+00:00 [queued]>
[2024-12-12T11:30:01.578+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-12T11:30:01.588+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): scrape_rtve_task> on 2024-12-12 05:30:00+00:00
[2024-12-12T11:30:01.592+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=16813) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-12T11:30:01.593+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rtve_schedule_scraper', 'scrape_rtve_task', 'scheduled__2024-12-12T05:30:00+00:00', '--job-id', '2361', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve_selenium.py', '--cfg-path', '/tmp/tmph56zm7n2']
[2024-12-12T11:30:01.596+0000] {standard_task_runner.py:72} INFO - Started process 16818 to run task
[2024-12-12T11:30:01.596+0000] {standard_task_runner.py:105} INFO - Job 2361: Subtask scrape_rtve_task
[2024-12-12T11:30:01.627+0000] {task_command.py:467} INFO - Running <TaskInstance: rtve_schedule_scraper.scrape_rtve_task scheduled__2024-12-12T05:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-12T11:30:01.680+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rtve_schedule_scraper' AIRFLOW_CTX_TASK_ID='scrape_rtve_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T05:30:00+00:00'
[2024-12-12T11:30:01.681+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T11:30:09.274+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-12T11:30:09.274+0000] {logging_mixin.py:190} INFO - Escrito el xmltv del canal "La 1"
[2024-12-12T11:30:11.366+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-12T11:30:11.367+0000] {logging_mixin.py:190} INFO - Escrito el xmltv del canal "La 2"
[2024-12-12T11:30:13.339+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-12T11:30:13.340+0000] {logging_mixin.py:190} INFO - Escrito el xmltv del canal "Teledeporte"
[2024-12-12T11:30:15.553+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-12T11:30:15.553+0000] {logging_mixin.py:190} INFO - Escrito el xmltv del canal "24 horas"
[2024-12-12T11:30:19.306+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-12T11:30:19.307+0000] {logging_mixin.py:190} INFO - Escrito el xmltv del canal "Clan"
[2024-12-12T11:30:19.385+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-12T11:30:19.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T11:30:19.392+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rtve_schedule_scraper, task_id=scrape_rtve_task, run_id=scheduled__2024-12-12T05:30:00+00:00, execution_date=20241212T053000, start_date=20241212T113001, end_date=20241212T113019
[2024-12-12T11:30:19.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-12T11:30:19.423+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-12T11:30:19.424+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
