[2024-12-14T23:30:05.392+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-14T23:30:05.403+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: la_otra_schedule_scraper.push_all_in_one scheduled__2024-12-14T17:30:00+00:00 [queued]>
[2024-12-14T23:30:05.409+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: la_otra_schedule_scraper.push_all_in_one scheduled__2024-12-14T17:30:00+00:00 [queued]>
[2024-12-14T23:30:05.409+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-14T23:30:05.416+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-14 17:30:00+00:00
[2024-12-14T23:30:05.421+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=892) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T23:30:05.422+0000] {standard_task_runner.py:72} INFO - Started process 893 to run task
[2024-12-14T23:30:05.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'la_otra_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-14T17:30:00+00:00', '--job-id', '2488', '--raw', '--subdir', 'DAGS_FOLDER/dag_la_otra.py', '--cfg-path', '/tmp/tmpwnactq0c']
[2024-12-14T23:30:05.424+0000] {standard_task_runner.py:105} INFO - Job 2488: Subtask push_all_in_one
[2024-12-14T23:30:05.448+0000] {task_command.py:467} INFO - Running <TaskInstance: la_otra_schedule_scraper.push_all_in_one scheduled__2024-12-14T17:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-14T23:30:05.491+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='la_otra_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T17:30:00+00:00'
[2024-12-14T23:30:05.492+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-14T23:30:07.944+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-14T23:30:07.945+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-14T23:30:07.950+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-14T23:30:07.951+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=la_otra_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-14T17:30:00+00:00, execution_date=20241214T173000, start_date=20241214T233005, end_date=20241214T233007
[2024-12-14T23:30:07.961+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-14T23:30:07.970+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T23:30:07.971+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
