[2024-12-09T23:30:20.806+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T23:30:20.815+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-09T17:30:00+00:00 [queued]>
[2024-12-09T23:30:20.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-09T17:30:00+00:00 [queued]>
[2024-12-09T23:30:20.821+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-09T23:30:20.827+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-09 17:30:00+00:00
[2024-12-09T23:30:20.831+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=7201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T23:30:20.832+0000] {standard_task_runner.py:72} INFO - Started process 7202 to run task
[2024-12-09T23:30:20.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rtve_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-09T17:30:00+00:00', '--job-id', '2261', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve_selenium.py', '--cfg-path', '/tmp/tmpfw0475pk']
[2024-12-09T23:30:20.834+0000] {standard_task_runner.py:105} INFO - Job 2261: Subtask push_all_in_one
[2024-12-09T23:30:20.858+0000] {task_command.py:467} INFO - Running <TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-09T17:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-09T23:30:20.907+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rtve_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-09T17:30:00+00:00'
[2024-12-09T23:30:20.908+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T23:30:23.317+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-09T23:30:23.318+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T23:30:23.324+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T23:30:23.324+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rtve_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-09T17:30:00+00:00, execution_date=20241209T173000, start_date=20241209T233020, end_date=20241209T233023
[2024-12-09T23:30:23.372+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T23:30:23.380+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T23:30:23.382+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
